server:
  servlet:
    context-path: /
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    generate-ddl: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/spike-evento
#    username: postgres
#    password: postgres
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password